version: '3.8'

services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: cinema_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3307:3306'  # Expose MySQL on port 3307
    volumes:
      - mysql_data:/var/lib/mysql  # Persist database data

volumes:
  mysql_data:

