spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 177532910468-kur3mjbge0ki7sq37c6shqn1a0g7v72b.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
  datasource:
    url: jdbc:mysql://cinema-booking-db.c5sa8iqk4ad3.us-east-2.rds.amazonaws.com:3306/cinema_db?useSSL=false&serverTimezone=UTC
    username: admin
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

